services:
  - type: pserv
    name: wellspace-postgres
    plan: free
    envVars:
      - key: POSTGRES_DB
        value: wellspace
      - key: POSTGRES_USER
        value: wellspace_user

  - type: web
    name: wellspace-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DB_URL
        fromService:
          type: pserv
          name: wellspace-postgres
          property: internalConnectionString
      - key: POSTGRES_USER
        fromService:
          type: pserv
          name: wellspace-postgres
          envVarKey: POSTGRES_USER
      - key: POSTGRES_PASSWORD
        fromService:
          type: pserv
          name: wellspace-postgres
          envVarKey: POSTGRES_PASSWORD
      - key: SPRING_PROFILES_ACTIVE
        value: docker