databases:
  - name: wellspace-postgres
    plan: free
    databaseName: wellspace
    user: wellspace_user

services:
  - type: web
    name: wellspace-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DB_URL
        fromDatabase:
          name: wellspace-postgres
          property: connectionString
      - key: POSTGRES_USER
        fromDatabase:
          name: wellspace-postgres
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: wellspace-postgres
          property: password
      - key: SPRING_PROFILES_ACTIVE
        value: docker